# Generated by Django 4.1.7 on 2023-03-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default='', max_length=10000),
            preserve_default=False,
        ),
    ]
